/** Filesystem vocabulary exposed to the application by its local host. */
export {
  AGENTS_DIR,
  CLARVIS_DIR,
  DIR_MODE,
  FILE_MODE,
  MARKETPLACE_FILE,
  SHORT_SCRATCH_BUDGET_BYTES,
  UNIX_SOCKET_PATH_BUDGET_BYTES,
  WORKSPACE_ENV,
  agentsMarketplaceFile,
  agentsMarketplaceFiles,
  allocateShortTemporaryRoot,
  ancestorTrust,
  ensureWorkspaceDir,
  ensureWorkspaceLocalDir,
  globalPaths,
  globalRoot,
  isAgentsMarketplaceFile,
  ownerFromWorkspace,
  shortTemporaryRootCandidates,
  unixSocketPathFits,
  workspacePaths,
  workspaceRoot,
  workspaceStatePaths,
  worktreeCheckoutRoot,
  writeFileAtomic,
  writeFileAtomicSync,
  type GlobalPaths,
  type ShortTemporaryRoot,
  type WorkspacePaths,
  type WorkspaceStatePaths,
} from "@clarvis/paths";
